# Generated by Django 5.2.8 on 2025-11-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'todos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['completed'], name='todos_complet_160b4e_idx'), models.Index(fields=['priority'], name='todos_priorit_88b18c_idx'), models.Index(fields=['due_date'], name='todos_due_dat_ca5942_idx')],
            },
        ),
    ]
